name: ci
on: [push]
jobs:
  go-dependency-consumer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - run: go mod tidy
      - run: go test -v .
      - run: go run main.go Max
      - run: go build -o app && ./app
      - run: GOPATH="$(pwd):$HOME/go/bin" go install .
      - run: ./bin/go-dependency-consumer
      - run: ./bin/go-dependency-consumer Maksimko
